# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  image: sampleapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'K8SExamplesACR'
        repository: '$(image)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    imagePullSecretName: k8sexamplesacrauth
  jobs:
    - job: Deploy
      displayName: Deploy to K8S
      pool:
        vmImage: ubuntu-latest  
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          targetPath: '$(Pipeline.Workspace)'
      - task: KubernetesManifest@0
        displayName: Create Secret for ACR
        inputs:
          action: 'createSecret'
          kubernetesServiceConnection: 'K8S_Examples_cluster-default'
          namespace: 'default'
          secretType: 'dockerRegistry'
          secretName: '$(imagePullSecretName)'
          dockerRegistryEndpoint: 'K8SExamplesACR'
      - task: KubernetesManifest@0
        displayName: Deploy to AKS
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'K8S_Examples_cluster-default'
          namespace: 'default'
          manifests: |
            $(Pipeline.Workspace)/manifests/deployment.yml
            $(Pipeline.Workspace)/manifests/service.yml
          imagePullSecrets: '$(imagePullSecretName)'
